config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create show index]
  resources :sessions, only: %i[new create destroy]
  resources :events, only: %i[new create index show]
  root to: 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :atendee, class_name: :User
  belongs_to :attended_event, class_name: :Event
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :title, :description, :venue, :date

  belongs_to :creator, class_name: 'User', foreign_key: :creator_id

  has_many :attendances, foreign_key: :attended_event_id
  has_many :atendees, through: :attendances

  scope :previous_events, -> { where('date < ?', Time.now) }
  scope :upcoming_events, -> { where('date > ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  has_many :created_events, foreign_key: :creator_id, class_name: :Event
  has_many :attendances, foreign_key: :atendee_id
  has_many :attended_events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @all_upcoming_events = Event.upcoming_events
    @all_past_events = Event.previous_events
  end

  def new
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.created_events.build(event_params)
    if @event.save
      redirect_to events_path, notice: 'Event created!'
    else
      flash[:notice] = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def attend
    @event = Event.find(params[:id])
    current_user.attended_events << @event
    redirect_to @event
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :venue, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_name(params[:name])
    if @user
      session[:user_id] = @user.id
      session[:name] = @user.name
      redirect_to root_path
      flash.notice = 'Logged in!'
    else
      flash.alert = 'Invalid user name'
      render 'sessions#new'
    end
  end

  def destroy
    session.delete(:name)
    session.delete(:user_id)
    session[:user_id] = nil
    redirect_to root_path
    flash.notice = 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if session[:name].nil?
      @user = User.new
    else
      @user = User.find(session[:user_id])
      redirect_to user_path(@user)
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'Successfully signed up!'
    else
      render :new
    end
  end

  def show
    return unless current_user

    @user_created_events = current_user.created_events
    @past_events = current_user.attended_events.select { |t| t.date.to_s < Time.now.to_s }
    @upcoming_events = current_user.attended_events.select { |t| t.date.to_s > Time.now.to_s }
  end

  def destroy
    session.delete(:id)
    @current_user = nil
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<h1> All Events </h1>

<section class="events-wrapper">
  <div class="upcoming-events">
    <h2>Upcoming Events</h2>
    <%if @all_upcoming_events.any? %>
      <% @all_upcoming_events.each do |e| %>
        <ul>
          <li> Title: <%= e.title %></li>
          <li> Description: <%= e.description %></li>
          <li> Venue: <%= e.venue %></li>
          <li> Date: <%= e.date %></li>
        </ul>
      <% end %>
    <% else %>
      <p>There are no upcoming events</p>
    <% end %>
  </div>
  <div class="past-events">
    <h2>Past Events</h2>
    <%if @all_past_events.any? %>
      <% @all_past_events.each do |e| %>
        <ul>
          <li> Title: <%= e.title %></li>
          <li> Description: <%= e.description %></li>
          <li> Venue: <%= e.venue %></li>
          <li> Date: <%= e.date %></li>
        </ul>
      <% end %>
    <% else %>
      <p>There are no past events</p>
    <% end %>
  </div>
</section>

<% if session[:name] %>
  <%= link_to "Create new event", new_event_path %><br><br>
  <%= link_to "Back to all your attended Events", root_path %>
<% else %>
  <%= link_to "Create new event", root_path %><br><br>
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event, method: "POST" do |f| %>
  <%= f.text_field(:title, placeholder: "Event Title") %>
  <%= f.text_field(:description, placeholder: "Event Description") %>
  <%= f.text_field(:venue, placeholder: "Event Venue") %>
  <%= f.date_field(:date, placeholder: "Event Date") %>
  <%= f.submit("Create Event") %>
<% end %>

app/views/events/show.html.erb
<h1>Creator Page</h1>
<p>the creater of the events is: <%= @event.creator.name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <p> <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= form_with model: @user do |f| %>
  <%= label_tag(:name, "Please fill in your name:") %>
  <br>
  <%= f.text_field(:name, placeholder: 'Name') %>
  <br>
  <br>
  <%= f.submit('Create account') %>
<% end %>

app/views/users/show.html.erb
<nav>
  <% if session[:name] %>
    <%= link_to  "Log Out", session_path(session[:name]), method: :delete %><br>
    <br>
    <p>You are Log In as: <br> <strong> <%= session[:name] %></strong></p>
    
    <%= link_to "Create new event", new_event_path %><br><br>
  <% else %>
    <p>You need to Log In or Sign Up</p>
    <%= link_to  "Log In", new_session_path%>
    <%= link_to  "Sign Up", new_user_path%> <br>
  <% end %>
  <%= link_to  "See all Events", events_path%> <br>
</nav>


<% if session[:name] %>
<% if @user_created_events.any? %>
  <div class="my-events-cont">
    <h2>Created Events</h2>
    <ul class="my-events">
      <% @user_created_events.each do |me| %>
        <li>
        <%= me.title %>
        </li>
        <li>
        <%= me.description %>
        </li>
        <li>
        <%= me.venue %>
        </li>
        <li>
        <%= me.date %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @past_events.any? %>
  <div class="my-events-cont">
    <h2>Past Events</h2>
    <ul class="my-events">
      <% @past_events.each do |me| %>
        <li>
        <%= me.title %>
        </li>
        <li>
        <%= me.description %>
        </li>
        <li>
        <%= me.venue %>
        </li>
        <li>
        <%= me.date %>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <p>There is no Past attended Events on the list</p>
<% end %>

<% if @upcoming_events.any? %>
  <div class="my-events-cont">
    <h2>Upcoming Events</h2>
    <ul class="my-events">
      <% @upcoming_events.each do |me| %>
        <li>
        <%= me.title %>
        </li>
        <li>
        <%= me.description %>
        </li>
        <li>
        <%= me.venue %>
        </li>
        <li>
        <%= me.date %>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <p>There is no Upcoming attended Events on the list</p>
<% end %>
<% end %>